### Название скрипта: Объединение скачанных городов в один файл

#### Описание:
    Скрипт объединения скачанных городов в один файл для дальнейшего использования в работе.

#### Основные функции:
    - Загрузка библиотек
    - Объединение городов и сохранение в один файл
    - Базовая проверка полученного файла

#### Использование:
    Kudinov_pogoda_goroda название файла с городами

#### Требования:
    - Python 3.10+
    - Зависимости: pandas, os

In [1]:
import pandas as pd
import os # импортирует модуль os — стандартный модуль для работы с операционной системой

In [2]:
# Код для объединения выгрузок в 1 файл

# Путь к директории в базе данных
path = "D:/DA_42_Learning/Script pogody/My_code/Goroda"

# задаем пустой список
csv_lst = []
# создаем цикл с добавлением нового города в конец списка и объединяем
for i in os.listdir(path):
    csv_lst.append(pd.read_csv(path+'\\'+i))
df = pd.concat(csv_lst)

# сохраняем файл
df.to_csv('Kudinov_pogoda_goroda.csv', encoding='utf8', index=False)

In [3]:
pc_csv = 'D:/DA_42_Learning/Script pogody/My_code/Kudinov_pogoda_goroda.csv'
jupyter_csv = 'http://localhost:8888/files/Kudinov_pogoda_goroda.csv?_xsrf=2%7C80ad8d51%7C51a158ace03bc161ff10db836dc874f8%7C1748885779'

In [7]:
# Загружаем данные
for file_path in [pc_csv, jupyter_csv]:
    try:
        data = pd.read_csv(file_path)
        break # если файл успешно загружен, выходим из цикла
    except FileNotFoundError:
        continue # если файл не найден, пробуем следующий
    else:
        print('Оба файла не найдены')
        print('Проблема с загрузкой')

In [8]:
data.head()

,date,city,temperature_2m,relative_humidity_2m,rain,snowfall,snow_depth,is_day,precipitation,wind_direction_100m,wind_speed_100m
0,1974-12-31 21:00:00,Ачинск,-18.753000,82.40408,0.0,0.0,0.79,0,0.0,210.69965,13.397612
1,1975-01-01 03:00:00,Ачинск,-17.853000,81.12036,0.0,0.0,0.79,1,0.0,210.73541,15.496736
2,1975-01-01 09:00:00,Ачинск,-16.853000,81.27107,0.0,0.0,0.79,1,0.0,214.87540,14.480773
3,1975-01-01 15:00:00,Ачинск,-18.703001,81.34388,0.0,0.0,0.79,0,0.0,193.17256,17.377226
4,1975-01-01 21:00:00,Ачинск,-18.353000,79.64939,0.0,0.0,0.79,0,0.0,174.28950,21.707731

In [9]:
# Проверим основные данные о файле с помощью функции
def date_info(date_table):
    '''Находим общую инфрмацию об исследуемом датафрейме с помощью функций info, describe, shape, duplicated()
    и выводим количество пропусков по столбцам с помощью функции for.
    '''

    print('\033[1m' + 'Общая информация о датафрейме и типы данных:' + '\033[0m')
    display(date_table.info())
    print('\033[1m' + 'Описательная статистика столбцов датафрейма методом describe:' + '\033[0m')
    display(date_table.describe())
    duplicate_dict = {}
    isnull_dict = {}
    for value in date_table.columns:
        duplicate_dict[value] = date_table[value].duplicated().sum()
        isnull_dict[value] = date_table[value].isnull().sum()
        tmp_df = pd.DataFrame([isnull_dict])
    tmp_df.index = ['Пропусков в столбце']
    tmp_df = tmp_df.style.map(lambda x: 'color:darkred' if x > 0 else 'color:dark')
    print('\033[1m' + 'Количество пропусков по столбцам:' + '\033[0m')
    display(tmp_df)
    '''опять'''
    print('\033[1m' + 'Количество строк = ' + '\033[0m', f'{date_table.shape[0]}')
    print('\033[1m' + 'Количество столбцов =' + '\033[0m', f'{date_table.shape[1]}\n')
    result_total = print('\033[1m' + 'Явных дубликатов в датафрейме =' + '\033[0m', date_table.duplicated().sum())
    return result_total
date_info(data)

Общая информация о датафрейме и типы данных:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2651616 entries, 0 to 2651615
Data columns (total 11 columns):
 #   Column                Dtype
---  ------                -----
 0   date                  object
 1   city                  object
 2   temperature_2m        float64
 3   relative_humidity_2m  float64
 4   rain                  float64
 5   snowfall              float64
 6   snow_depth            float64
 7   is_day                int64
 8   precipitation         float64
 9   wind_direction_100m   float64
 10  wind_speed_100m       float64
dtypes: float64(8), int64(1), object(2)
memory usage: 222.5+ MB

None

Описательная статистика столбцов датафрейма методом describe:

,temperature_2m,relative_humidity_2m,rain,snowfall,snow_depth,is_day,precipitation,wind_direction_100m,wind_speed_100m
count,2.651616e+06,2.651616e+06,2.651616e+06,2.651616e+06,2.651472e+06,2.651616e+06,2.651616e+06,2.651616e+06,2.651616e+06
mean,5.662723e+00,7.472857e+01,3.042152e-01,7.457339e-02,1.136675e-01,5.133760e-01,4.003094e-01,1.922891e+02,2.092749e+01
std,1.282342e+01,1.686180e+01,1.212679e+00,3.395171e-01,1.998770e-01,4.998211e-01,1.299417e+00,9.730081e+01,9.921159e+00
min,-5.583300e+01,7.472527e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.010310e-01,0.000000e+00
25%,-2.522500e+00,6.439220e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.080043e+02,1.370839e+01
50%,6.137000e+00,7.860572e+01,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,2.038059e+02,2.034557e+01
75%,1.559800e+01,8.791099e+01,0.000000e+00,0.000000e+00,1.500000e-01,1.000000e+00,1.000000e-01,2.738140e+02,2.721038e+01
max,4.078950e+01,1.000000e+02,9.220001e+01,1.757000e+01,1.380000e+00,1.000000e+00,9.220001e+01,3.600000e+02,9.889587e+01

Количество пропусков по столбцам:

Количество строк =  2651616
Количество столбцов = 11

Явных дубликатов в датафрейме = 0

In [10]:
# Основные данные столбца
def date_info_loc(date_table_loc):
    '''Для обработки столбца перед исследовательским анализом нахожу по каждому столбцу его описательную статистику функцией describe,
    дубликаты функцией duplicated, частоту уникальных значений функцией value_counts, уникальные значения функцией unique,
    пропуски по столбцу функцией isnull.
    '''

    title = date_table_loc,
    print('\033[1m' + 'Описательная статистика столбца датафрейма методом describe:' + '\033[0m'),
    display(date_table_loc.describe()),
    print('\033[1m' + 'Количество дубликатов по столбцу:' + '\033[0m'),
    display(date_table_loc.duplicated().sum())
    print('\033[1m' + 'Частота уникальных значений по столбцу:' + '\033[0m'),
    display(date_table_loc.value_counts().head(10)),
    print('\033[1m' + 'Процентное отношение уникальных значений по столбцу:' + '\033[0m'),
    display(round(date_table_loc.value_counts(normalize=True).to_frame().head(10)*100, 3)),
    print('\033[1m' + 'Уникальные значения:' + '\033[0m'),
    display(date_table_loc.unique())
    print('\033[1m' + 'Пропуски по столбцу:' + '\033[0m'),
    display(data.loc[date_table_loc.isnull() == True])
    return
date_info_loc(data['city'])

Описательная статистика столбца датафрейма методом describe:

count     2651616
unique         36
top        Ачинск
freq        73656
Name: city, dtype: object

Количество дубликатов по столбцу:

2651580

Частота уникальных значений по столбцу:

city
Ачинск          73656
Армавир         73656
Оренбург        73656
Орск            73656
Пермь           73656
Рубцовск        73656
Рязань          73656
Северодвинск    73656
Ставрополь      73656
Томск           73656
Name: count, dtype: int64

Процентное отношение уникальных значений по столбцу:

              proportion
city
Ачинск             2.778
Армавир            2.778
Оренбург           2.778
Орск               2.778
Пермь              2.778
Рубцовск           2.778
Рязань             2.778
Северодвинск       2.778
Ставрополь         2.778
Томск              2.778

Уникальные значения:

array(['Ачинск', 'Армавир', 'Астрахань', 'Балаково', 'Батайск',
       'Хасавюрт', 'Черкесск', 'Жуковский', 'Димитровград',
       'Электросталь', 'Кисловодск', 'Королёв', 'Краснодар',
       'Красногорск', 'Красноярск', 'Люберцы', 'Махачкала', 'Москва',
       'Мытищи', 'Находка', 'Оренбург', 'Орск', 'Пермь', 'Рубцовск',
       'Рязань', 'Северодвинск', 'Ставрополь', 'Томск',
       'Великий Новгород', 'Волжский', 'Вологда', 'Якутск', 'Йошкар-Ола',
       'Южно-Сахалинск', 'Зеленодольск', 'Златоуст'], dtype=object)

Пропуски по столбцу:

Empty DataFrame
Columns: [date, city, temperature_2m, relative_humidity_2m, rain, snowfall, snow_depth, is_day, precipitation, wind_direction_100m, wind_speed_100m]
Index: []